# Generated by Django 5.2.7 on 2025-11-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views",
            field=models.PositiveIntegerField(default=0, verbose_name="阅读量"),
        ),
    ]
